### ISSUE TITLE
Super Excited for this!

### ISSUE THREAD

**Issue by Fakiee** [renzuzu/renzu_tuners#1]
Will this have the same or similar functions that QB-TunerChip has? I love Renzu_Stancer alot, and Im hoping this will replace Tunerchip for me! (Obviously it will have more than Tunerchip but will it have what Tunerchip has?)

**Comment by renzuzu** [comment]
this is almost done, im just finalizing things
 
 this includes dyno and Tuning.
 this dont have a tuner like qb-tuning or tuner-laptop in the past.
 only related to engine can be tuned. l
 
 no related to  wheels

**Comment by ElusionPDX** [comment]
Will this be qb and esx or just eax

**Comment by renzuzu** [comment]
both ofcourse.
only simple resource i didnt bother creating bridge to other framework.

**Comment by ElusionPDX** [comment]
Will your engine resource be updated to link in some how. So we can replace the engine with sounds and power and then tune the engine

**Comment by renzuzu** [comment]
renzu_engine,renzu_turbo,renzu_nitro is connected to this resource,  (if its only started)
there is a ECU item/mode in the resource where you can tune the current engine.
while in dyno you can preview your vehicle, horsepower, torque and topspeed.

let me know if you have some suggestion before i can make this public

heres the upgrade menu
![image](https://user-images.githubusercontent.com/82306584/219555578-84338e3d-aab4-4420-8523-3f992622d4c4.png)
![image](https://user-images.githubusercontent.com/82306584/219555614-237a1625-3209-44f1-87ae-92b4db681003.png)
![image](https://user-images.githubusercontent.com/82306584/219555639-7c76c8a2-3b51-4d31-a068-2dd1918680f5.png)
![image](https://user-images.githubusercontent.com/82306584/219555710-104978b3-e73c-4737-be0b-d4f916432d1e.png)
![image](https://user-images.githubusercontent.com/82306584/219555739-57437d67-e9e5-4788-96fb-d6cce53be5c4.png)
![image](https://user-images.githubusercontent.com/82306584/219555774-b7fdbe90-2297-474b-b6a7-29775520423b.png)
![image](https://user-images.githubusercontent.com/82306584/219555801-d201bec1-d927-4207-9e7b-4342cadb4608.png)

all of this is craftable.

**Comment by ElusionPDX** [comment]
Add random engine sensors for mechs to trouble shoot and replace.  Cam,
crank sensors
O2 sensors. Maybe work the engine temperature native into the script for
bad radiator and temperature sensors.
Add a scanner tool to read trouble codes for engine lights.  Like I can go
on and on with this stuff lol

**Comment by ElusionPDX** [comment]
Fun codes like this to make the system feel more real for mechanics and give it more depth.  https://repairpal.com/obd-ii-code-chart

**Comment by renzuzu** [comment]
cant view the link you sent.
OBD2 code is for debuging engine codes right?

if i have to add those sensors as well i need UI.
or probably can use oxlib for that tool.

random engine sensor is possible as i can make this appear when specific parts is degraded.

as for engine,water temp, oil temp
we can do circumvent some logic.
GetVehicleDashboardOilTemp
GetVehicleDashboardOilPressure
GetVehicleOilLevel
for engine and water, can use native GetVehicleEngineTemperature
there is no setter for oil temp so this can be view only

**Comment by ElusionPDX** [comment]
I had a engine temp and oil system. I'll send you it over discord. Never got the oil the way I wanted so I cheated and just set the oil value when damage would happen.  Engine cooling was changed based on speed and rpm. To high rpm with stock cooling would cause over heating. Once engine over heated it would cause damage to the engine and at X level die or explode 😂

**Comment by renzuzu** [comment]
im actually thinking if its worth it to add over heating , its a plus in this resource so it can degrade most of engine parts instantly when its happen,

but in my experience player dislaikes overheating logic, probably because its too fast to get overheated :D

how can i add you in discord?

**Comment by Fakiee** [comment]
HOLY SHI* GGS RENZU! THIS SCRIPT IS GONNA BE SO SICK!

**Comment by Fakiee** [comment]
Renzu, Do you have a discord server?

**Comment by renzuzu** [comment]
> Renzu, Do you have a discord server?

i dont have discord server. sorry
i am avalable via discord messaging in private.

**Comment by Fakiee** [comment]
Would you mind I add you? or you add me: Fakiee#8761

**Comment by renzuzu** [comment]
i tried adding you , but its said your friend is max :D

**Comment by Fakiee** [comment]
Ahh it turns out I had a ton of in coming request. I went through and cleared them. Hopefully works now. Fakiee#8761

**Comment by darkstargr28** [comment]
im waiting for this a long <3 very nice work again renzuzu <3

**Comment by renzuzu** [comment]
before i created this repo, this is already done.
the only thing it taking time now because i added dyno and reworked the tuning system to semi realistic.
with afr, compressions, ignition timing, etc..

**Comment by Fakiee** [comment]
That would be awesome! I would love to test it

**Comment by ElusionPDX** [comment]
> before i created this repo, this is already done. the only thing it taking time now because i added dyno and reworked the tuning system to semi realistic. with afr, compressions, ignition timing, etc.. i can probably release a beta version only in github, so i can ask some help on testing.. :D

Post that beta man. I'll test the shit out of it 😁😁

**Comment by Alohaaaaaaa** [comment]
> before i created this repo, this is already done. the only thing it taking time now because i added dyno and reworked the tuning system to semi realistic. with afr, compressions, ignition timing, etc.. i can probably release a beta version only in github, so i can ask some help on testing.. :D

It would be awesome to have the beta to test it out.

**Comment by Fakiee** [comment]
> before i created this repo, this is already done. the only thing it taking time now because i added dyno and reworked the tuning system to semi realistic. with afr, compressions, ignition timing, etc.. i can probably release a beta version only in github, so i can ask some help on testing.. :D

Yooo, Try and add me again, it should work: Fakiee#8761. Would love to test this out as I stated above

**Comment by renzuzu** [comment]
today i might release a beta.
and since there will be 1000 items here.
just one final task about inventory supports.
whats the most popular inventory in qbcore? qb-inv?

**Comment by Fakiee** [comment]
> today i might release a beta.
> and since there will be 1000 items here.
> just one final task about inventory supports.
> whats the most popular inventory in qbcore? qb-inv? 
> its just sad to see, qb-inv does not support Label in metadata, or i am wrong..

I know LJ is one of the most popular free ones

**Comment by renzuzu** [comment]
i will just support it anyway, as qbcore supports item info. but no label.
i will suggest my forked qb inv, this supports item infi label and images etc., or they should use custom crafting resource that supports metadata. or just use ox_inv

**Comment by renzuzu** [comment]
beta is released, please test and create new issue if you found issue and suggestions 💟

**Comment by ElusionPDX** [comment]
> i will just support it anyway, as qbcore supports item info. but no label. i will suggest my forked qb inv, this supports item info label and images etc., or they should use custom crafting resource that supports metadata. or just use ox_inv

Make it a config choice as not everyone runs ox crap when using qb. Only qBox is shipping with OX, stuff but the main qb repo is only shipping with qb invy and target

**Comment by renzuzu** [comment]
so you prefer qb-menu and qb-target right?? also callbacks, no ox_lib at all?

**Comment by ElusionPDX** [comment]
using OX is good for esx users but the main qb repo ships with qb-target. So having two systems run a target would be a pain as the user would need to update from qb-target  to ox on every script or change yours to work with qbtarget.

**Comment by renzuzu** [comment]
i did support qb-inventory , qbtarget and possible qtarget  too.
https://github.com/renzuzu/renzu_tuners/commit/ed95f4536a1ae24d2f27d7e44cbad3a08478f9f9

**Comment by renzuzu** [comment]
> radiator,coolants,

this  what i am looking to add in near future.

thank

closing for now.
