### ISSUE TITLE
Dynojet 'E' command not working

### ISSUE THREAD

**Issue by zjdaniels1985** [renzuzu/renzu_tuners#12]
1. Worked before last pull request
2. The active job is set for mechanic@5 and tried with tuners@3
3. The marker shows up and the local dynjet is present 

- While in the vehicle i drive to the dynojet marker and the E command renders on the screen when I press 'E' nothing happens and no errors are present in console output

**Comment by renzuzu** [comment]
![image](https://user-images.githubusercontent.com/82306584/226526261-a043ce2f-d43a-4dc6-8fc0-283daafd80f3.png)

what framework?

can you check if the grade is correct.

**Comment by zjdaniels1985** [comment]
qbcore framework and however i noticed that even when i use /setjob 1 mechanic 5     the database shows a 0 grade level? I also don't see that qbcore has grade levels for mechanics.

**Comment by renzuzu** [comment]
yea thats the point i misconfigured the config for esx. since esx have atleast 7 iirc.

so you can set that to 4 (qbcore boss) or 1

**Comment by AnxietyPills** [comment]
it just makes the dyno double up everytime "e" is pressed? like it spawns another dyno prop ontop the one thats already there, it doesn't put the car on the dyno at all nor does it open any of the menus

**Comment by zjdaniels1985** [comment]
> yea thats the point i misconfigured the config for esx. since esx have atleast 7 iirc.
> 
> so you can set that to 4 (qbcore boss) or 1

I change the level and see what happens
