### ISSUE TITLE
addon cars 

### ISSUE THREAD

**Issue by Gowie22** [renzuzu/renzu_tuners#17]
Could be just me but i cant get add on cars to work on the dyno and cant find where i need to add them. Any help would be much appreciated

**Comment by renzuzu** [comment]
this is tested in Custom cars and default.
there should be not any conflict.

whta exactly is your issue? maybe i can guide

**Comment by Gowie22** [comment]
Thats what i thought as i watched the videos.

I drive up to the dyno and press E and nothing happens just sit there saying press E when im in any custom car ive tried multiple times . Default car will get on the dyno and work fine

**Comment by renzuzu** [comment]
can you send the link to custom vehicle?
what type of vehicle?

**Comment by Gowie22** [comment]
https://www.gta5-mods.com/vehicles/nissan-skyline-gt-r-r32-5-wide-rims-mreverest

sports

**Comment by Gowie22** [comment]
have gotten it to work with custom cars have to restart the resource after i restart the server
