### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by HiTTA757** [renzuzu/renzu_tuners#18]
![5AC4E073-B305-45C0-A8BA-130799DEDF7A](https://user-images.githubusercontent.com/127186414/227132553-6c79be93-89a5-42af-9ad2-a595b8c18bc3.jpeg)

Everything was working fine this morning before work. Got home and every time i buy a car, i can’t move nor get out the car and this is error that’s comes up.

**Comment by renzuzu** [comment]
update the resource this was already fix yesterday,

this is when the vehicle get deletes before they load up the stats
