### ISSUE TITLE
Errors any time i spawn a vehicle

### ISSUE THREAD

**Issue by Mackaelroni** [renzuzu/renzu_tuners#19]
![image](https://user-images.githubusercontent.com/64632545/227580731-488a8521-a20d-46b9-81a6-cba872f7e95d.png)

**Comment by Mackaelroni** [comment]
This is a fresh install of the script.

**Comment by renzuzu** [comment]
re open if this issue still exist in latest branch,

apprently this issue occur when i do refactor the ECU thing.
