### ISSUE TITLE
Stuff is degrading way too fast.

### ISSUE THREAD

**Issue by Mackaelroni** [renzuzu/renzu_tuners#21]
I have had the server up for maybe 2 hours and a car is already at 40% in terms of the parts. Where can I adjust degrading parts?

**Comment by renzuzu** [comment]
![image](https://user-images.githubusercontent.com/82306584/227755074-6ce878b4-5cb7-4e86-b34a-23a8020d0498.png)

take note untuned engine is always prompt to degration

**Comment by Mackaelroni** [comment]
how does one repair default tires?

**Comment by renzuzu** [comment]
the street tires is identical to Default
