### ISSUE TITLE
Crafting transformers ENGINE problem

### ISSUE THREAD

**Issue by nicolai11111** [renzuzu/renzu_tuners#24]
Trying to buy engine at engine shop, results in these errors. I dont lose money, or receive the engine. 
![image](https://user-images.githubusercontent.com/127895837/228844679-88ed9205-41ff-4c0b-8953-973221587c1b.png)

Also at the crafting point, where u can craft engines. I dont receive the engine, but i lose the items. 
![image](https://user-images.githubusercontent.com/127895837/228845148-f389b720-73f3-4b94-8d90-48c212cb3f10.png)

**Comment by nicolai11111** [comment]
Also, if you have more than one engine item in inventory, when installing. it takes all of them, instead of 1

**Comment by renzuzu** [comment]
the error line thrown is from renzu_engine
next time open to a correct repo.

make sure the item is `enginegago` is register to your ox_inventory.
```
['enginegago'] = {
    label = 'ENGINE',
    weight = 0,
    stack = false,
    close = true,
    description = ''
},
```

**Comment by nicolai11111** [comment]
My bad, i forgot to add the enginegago to ox! Thx!
