### ISSUE TITLE
too much queries ?!

### ISSUE THREAD

**Issue by necaz1337** [renzuzu/renzu_tuners#25]
hello renzu, why there are so much queries ?! I think can affect server performance on 200-300 players count, its kinda strange i think
![quer](https://user-images.githubusercontent.com/120249798/229364264-6082b312-6830-4a2e-ad9d-e192248ab06d.PNG)

i have ~ 10-20 queries per minute with one connected, imagine having more than 50

**Comment by renzuzu** [comment]
There are 2 queries per plate checking and updating.

Removing the select for checking can br done but its risky.

Ill try to change the saving logic.

For now the changed,

This should save only if vehicle is active state.
This has been accidentaly removed.

**Comment by renzuzu** [comment]
another changes: https://github.com/renzuzu/renzu_tuners/commit/474a89b535085c26f0d2032fc6ea81f772ea4b62

this now saves only if vehicle have some change on stats.
thank you for notifying me this..

this should be solved
