### ISSUE TITLE
suggestion 🥇 :) 

### ISSUE THREAD

**Issue by bbeckann** [renzuzu/renzu_tuners#3]
Hi brother . renzu_tuners by far the best script I'll leave a follow that being implemented would be very nice and functional too

uma barra como mostra a imagem abaixo seria muito interessante. mostrando km/quilômetro dependendo de qual escolher

or you consult with the job (mechanic) your km/mile.

![image](https://user-images.githubusercontent.com/95275692/223476567-93ff9b5e-d00d-4e7f-b375-421a8cd6a373.png)

Another suggestion would be the vehicle's oil level, I know it's already implemented in renzu_tuners, but a suggestion would be for any player to change the car's oil and when that car travels at a certain km/mile, the oil will run out if the player leaves the oil dropped a lot, the car broke down and it would have to be taken to a workshop.

well and just a suggestion , I know it takes time to program .. but would love to see this in a future update .

**Comment by renzuzu** [comment]
that is already implemented in degration.
degration means not vehicle health.
it degrades vehicle handling.

when you change the oil of vehicle the mileage will reset.
