### ISSUE TITLE
db issue i think

### ISSUE THREAD

**Issue by necaz1337** [renzuzu/renzu_tuners#34]
![Capture](https://user-images.githubusercontent.com/120249798/232248507-cef6f35c-6575-4694-b07f-853283b52076.PNG)

is this normal if i have only 4 vehicles in database and one single player online ? im using this on my test server and i dont know how will handle if 200+

**Comment by renzuzu** [comment]
this is tested with 100+ players without issue.
those warning are vary and depends on your system.

make sure you are using the latest main branch too, various optimsation 1-2 weeks ago if remember correctly
