### ISSUE TITLE
Errors relating to Update transaction database

### ISSUE THREAD

**Issue by zjdaniels1985** [renzuzu/renzu_tuners#4]
While performing upgrades getting this error from oxmysql for the 'advancedflags' column. 
![image](https://user-images.githubusercontent.com/19808462/224508579-c90428df-92ba-43db-a132-d93e77764cbc.png)

**Comment by renzuzu** [comment]
this is freaking mistake to make it as a varchar.

now if some of your vehicle with advancedflags column have already a data (possibly incomplete json)
you just need to replace it with '[]'
