### ISSUE TITLE
Error on fresh install

### ISSUE THREAD

**Issue by Tokolosh95** [renzuzu/renzu_tuners#6]
![image](https://user-images.githubusercontent.com/51271402/224561296-d8199a8a-33e3-4664-8105-cb688938141c.png)

Not made any changes just added it, issue relates to the below:

HasAccess = function()
	local job = PlayerData?.job?.name
	if not job then return end
	local access = config.job[PlayerData.job.name]
	if not config.job or access and access <= PlayerData.job.grade then
		return true
	end
	return false
end

**Comment by Mackaelroni** [comment]
I get the same error on load up.

**Comment by Mackaelroni** [comment]
if i have the mechanic job and load in, i get the error. if i dont, and change to mechanic after i load in, then it works just fine.

**Comment by renzuzu** [comment]
whats your config for this?

```
config.job = { -- set to false (config.job = false) if you want all feature are accesible by any player, or true, required job to use repairs and upgrade menu, dyno -- job access for menu upgrade and points. ex. mechanic, tuner?
	['mechanic'] = 5, -- @jobname -- @grade_level
	['tuners'] = 3, -- @jobname -- @grade_level
}
```

QBCORE?

**Comment by Tokolosh95** [comment]
The updated fixed the issue
