### ISSUE TITLE
Engine sounds and turbo issue

### ISSUE THREAD

**Issue by BrokeDaily** [renzuzu/renzu_tuners#9]
Hi there! The engine sounds and turbo upgrades do not stick to the car after placing in garage or after server restart. 
[ script:renzu_tuners] SCRIPT ERROR: [string "..."]:45: attempt to compare nil with number
[  script:renzu_turbo] table: 0x7f12825b6c70	100.0
[  script:renzu_turbo] SCRIPT ERROR: @renzu_turbo/server.lua:178: attempt to index a nil value (field '?')
[  script:renzu_turbo] > handler (@renzu_turbo/server.lua:178)
[  script:renzu_turbo] table: 0x7f1282aab930	99.85
[  script:renzu_turbo] SCRIPT ERROR: @renzu_turbo/server.lua:178: attempt to index a nil value (field '?')
[  script:renzu_turbo] > handler (@renzu_turbo/server.lua:178)
[  script:renzu_turbo] table: 0x7f127dcf1b10	99.7
[  script:renzu_turbo] SCRIPT ERROR: @renzu_turbo/server.lua:178: attempt to index a nil value (field '?')
[  script:renzu_turbo] > handler (@renzu_turbo/server.lua:178)
[  script:renzu_turbo] table: 0x7f12852a8100	99.55
[  script:renzu_turbo] SCRIPT ERROR: @renzu_turbo/server.lua:178: attempt to index a nil value (field '?')
[  script:renzu_turbo] > handler (@renzu_turbo/server.lua:178)
[  script:renzu_turbo] table: 0x7f1281cc1b70	99.4
[  script:renzu_turbo] SCRIPT ERROR: @renzu_turbo/server.lua:178: attempt to index a nil value (field '?')
[  script:renzu_turbo] > handler (@renzu_turbo/server.lua:178)
[  script:renzu_turbo] table: 0x7f12afd91c50	99.25
[  script:renzu_turbo] SCRIPT ERROR: @renzu_turbo/server.lua:178: attempt to index a nil value (field '?')
[  script:renzu_turbo] > handler (@renzu_turbo/server.lua:178)
[  script:es_extended] [INFO] Saved 1 player over 0.0 ms
[  script:renzu_turbo] table: 0x7f12af5dbbf0	99.1
[  script:renzu_turbo] SCRIPT ERROR: @renzu_turbo/server.lua:178: attempt to index a nil value (field '?')
[  script:renzu_turbo] > handler (@renzu_turbo/server.lua:178)

**Comment by renzuzu** [comment]
the latest renzu_turbo does not have 178 line.

use the latest version and open again if its still throwing errors. which should not happen.
